version: '3'

volumes:
  postgres:

services:
  db:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
  kong:
    image: kong
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=db"
    ports:
      - "127.0.0.1:8001:8001"
    depends_on:
      - db
    networks:
      - outside
      - default
  dashboard:
    image: pgbi/kong-dashboard
    networks:
      - default

networks:
  default:
    driver: overlay
  outside:
    external:
      name: rp
