version: '2'

volumes:
  postgres:

services:
  db:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
    volumes:
      - postgres:/var/lib/postgresql/data
  kong:
    image: kong
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=db"
    ports:
      - "80:8000"
      - "443:8443"
      - "127.0.0.1:8001:8001"
    expose:
       - 7946
       - 7946/udp
       - 8001
    depends_on:
      - db
    networks:
      - outside
      - default
  dashboard:
    image: pgbi/kong-dashboard

networks:
  outside:
    external:
      name: rp
